### ISSUE TITLE
avoid use of console.log in scripts - if it suppose to be part of the react native env

### ISSUE THREAD

**Issue by orenyodfat** [daostack/common-scripts#2]
https://reactnative.dev/docs/performance#using-consolelog-statements
e.g https://github.com/daostack/common-scripts/blob/master/createCommon.js#L18

**Comment by jellegerbrandy** [comment]
it is not supposed to be part of react-native env.
These are scripts we will use to trigger events, to check the sanity of the contract deployments, and as an example for the react native code, it will not be a package dependency of the common app. (at least not for now)
